export interface Employee {
  date: string;
  userGuid: string;
  isReadOnly: boolean;
  isCompleted: boolean;
  isOvertimeAllowed: boolean;
  expectedHours: number;
  enteredHours: number;
  isHoliday: boolean;
  holidayName: string | null;
  flextimeLimitPerDay: number | null;
  absenceHours: number;
  incompleteTimingMinutes: number;
  enteredTimeEntries: number;
}

export const employeeMockData: Employee[] = [
  {
    date: "2025-08-11",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-12",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-13",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-14",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-15",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-16",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-17",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-18",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-19",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-20",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-21",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-22",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-23",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-24",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-25",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 10,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-26",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 10,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-27",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 8,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-28",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-29",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-30",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-08-31",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-01",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-02",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-03",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-04",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-05",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-06",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-07",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-08",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-09",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 8.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-10",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 6.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-11",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 6.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-12",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 6.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-13",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-14",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-15",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 9.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-16",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 6,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-17",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-18",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-19",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-20",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-21",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-22",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-23",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-24",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-25",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-26",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-27",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-28",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-29",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 10,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-09-30",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 10,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-01",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 10,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-02",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 10,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-03",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 8,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-04",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-05",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-06",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-07",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-08",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 6,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-09",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-10",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-11",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-12",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-13",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-14",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-15",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-16",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-17",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-18",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-19",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-20",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-21",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 8,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-22",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-23",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 9,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-24",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 6.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-25",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0.0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-26",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 0.0,
    enteredHours: 0,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-27",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-28",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 7.25,
    isHoliday: false,
    holidayName: null,
    absenceHours: 0.0,
    flextimeLimitPerDay: null,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-29",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 8,
    isHoliday: true,
    holidayName: "national holiday",
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-30",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 6,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-10-31",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 9,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  },
  {
    date: "2025-11-03",
    userGuid: "0c6b0b15-15eb-a77b-ad09-61527abc7be6",
    isReadOnly: false,
    isCompleted: false,
    isOvertimeAllowed: false,
    expectedHours: 7.25,
    enteredHours: 8,
    isHoliday: false,
    holidayName: null,
    flextimeLimitPerDay: null,
    absenceHours: 0.0,
    incompleteTimingMinutes: 0,
    enteredTimeEntries: 0.0
  }
];

/*
 *
  Hours/Workhours:
    "workType": {
      "guid": "string",
      "name": "string",
      "code": "string"
    },
     "description": "string",
    "unitPrice": {
      "amount": 0,
      "currencyCode": "string",
       "isBillable": true,
    "billableStatus": "Billable",
    "isApproved": true,
    "overtime": {
      "guid": "string",
      "name": "string"
    },
    Users/Flextime:
    {
  "totalFlextimeBalance": 0,
  "monthFlextimeBalance": 0
  users/workdays:
   {
    "date": "2025-10-27",
    "userGuid": "string",
    "isReadOnly": true,
    "isCompleted": true,
    "isOvertimeAllowed": true,
    "expectedHours": 0,
    "enteredHours": 0,
    "isHoliday": true,
    "holidayName": "string",
    "flextimeLimitPerDay": 0,
    "absenceHours": 0,
    "incompleteTimingMinutes": 0,
    "enteredTimeEntries": 0
  }
    users/workcontracts/current:
     "title": "string",
  "startDate": "2025-10-27",
  "endDate": "2025-10-27",
  "dailyHours": 0,
  "isOvertimeAllowed": true,
  "isFlextimeActive": true,
  "flextimeLimitPerDay": 0,
  "workWeek": [
    "Monday"
  ],

}

 *
 */
